export LD_LIBRARY_PATH="$LD_LIBRARY_PATH_PYGPU_CUDA_BACKUP"
unset LD_LIBRARY_PATH_PYGPU_CUDA_BACKUP
export CPATH="$CPATH_CUDA_BACKUP"
unset CPATH_CUDA_BACKUP
export LIBRARY_PATH="$LIBRARY_PATH_CUDA_BACKUP"
unset LIBRARY_PATH_CUDA_BACKUP
